Translating blog-himarpl section to Bahasa Indonesia and fixing some words at getting-started and ascendia-himarpl
himarplupi/docs-himarpl pull request #5
Opened 2024-12-04 16:23 UTC by Zreaei

#### Description

- Closes # 
- What does this PR change? Give us a brief description.
- Did you change something visual? A before/after screenshot can be helpful.

2024-12-05 01:56 UTC, DikDns requested changes
Ada beberapa minor review, silakan di fix dulu

2024-12-05 01:56 UTC, DikDns commented on src/content/docs/id/ascendia-himarpl/03-folder-structure.mdx
> +- **hooks/**: _Custom_ React Hooks untuk logika bersama
logika bersama apaan anjir, aneh bet coba jangan `bersama`, mungkin logika _state management_ global
sekalian sama yang inggrisnya juga jadi tambahin state management

2024-12-05 01:56 UTC, DikDns commented on src/content/docs/id/ascendia-himarpl/05-rules-and-conventions.mdx
> +Jika Anda belum familiar dengan TypeScript, Anda bisa memeriksa artikel ini untuk mempelajari lebih lanjut : [Typescript untuk Pengembang React](https://elazizi.com/posts/how-to-learn-typescript-for-
developer aja lebih umum di Indonesia

2024-12-05 01:56 UTC, DikDns commented on src/content/docs/id/blog-himarpl/01-overview.mdx
> +[blog.himarpl.com](https://blog.himarpl.com) adalah platform blog resmi untuk anggota HIMARPL (Himpunan Mahasiswa Rekayasa Perangkat Lunak). Situs web ini dibangun menggunakan Next.js dengan T3 Stack
`pengurus` himarpl aja

2024-12-05 01:56 UTC, DikDns commented on src/content/docs/id/blog-himarpl/01-overview.mdx
> +- Editor Teks Keren dengan Antarmuka WYSIWYG
`rich` = tuh maksudnya penuh dengan fitur cari aja kata-katanya

2024-12-05 01:56 UTC, DikDns commented on src/content/docs/id/blog-himarpl/02-setup.mdx
> +   - Ikuti [Panduan Pembatasan Laju Upstash](https://upstash.com/docs/oss/sdks/ts/ratelimit/gettingstarted) untuk mendapatkan:
rate limitting jangan jadi laju pembatasan aneh

2024-12-05 01:56 UTC, DikDns commented on src/content/docs/id/blog-himarpl/02-setup.mdx
> +4. Atur _remote_ _upstream_:
remote ga perlu kan itu keyword command git, smaa yang lainnya juga kalo ada keyword cmd gaperlu italic

2024-12-05 01:56 UTC, DikDns commented on src/content/docs/id/blog-himarpl/03-folder-structure.mdx
> +Proyek ini mengikuti arsitektur [T3 Stack](https://create.t3.gg/) dengan [TipTap](https://tiptap.dev/) untuk pengeditan teks yang lebih keren. Struktur ini menekankan _type-safety_, modularitas, dan
ini juga pengeditan teks yang lebih keren apa jir, rich itu bukan keren

2024-12-05 01:56 UTC, DikDns commented on src/content/docs/id/blog-himarpl/05-rules-and-conventions.mdx
> +Jika Anda belum familiar dengan TypeScript, Anda bisa memeriksa artikel ini untuk mempelajari lebih lanjut : [Typescript untuk Pengembang React](https://elazizi.com/posts/how-to-learn-typescript-for-
developer

2024-12-06 03:44 UTC, DikDns commented
Kapan mau memperbaikinya @Zreaei ?

2024-12-09 03:59 UTC, Zreaei commented
> Kapan mau memperbaikinya @Zreaei ?

utiwi

2025-02-03 07:38 UTC, closed without merging